<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Book Bus Tickets Online at Lowest Price| Guzoye</title>
    <script
      src="https://kit.fontawesome.com/47080b3c1e.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="CSS/Stylesheet.css" />
    <link rel="icon" href="image/icon-logo.png" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <script>
      function myFunction() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
          x.className += " responsive";
        } else {
          x.className = "topnav";
        }
      }
    </script>
  </head>
  <body>
    <div class="topnav" id="myTopnav">
      <a href="index.php" class="active"
        ><img src="image/Logo-wz-bk.png" alt=""
      /></a>
      <a id="space"></a>
      <a href="index.php">Home</a>
      <a href="booking.php">My Booking</a>
      <a href="contact.php">Contact Us</a>
      <a href="Login.php"> <button>Login</button></a>
      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
      </a>
    </div>
    <!--Body-->
    <div id="path">
      <div>
        <a href="index.php">Home</a>
      </div>
      <div>
        <p>/ Terms and Conditions</p>
      </div>
    </div>
    <div id="about">
      <h2>Term and Conditions</h2>
      <p>
        This document is an electronic record in terms of the Information
        Technology Act, 2000 and rules made there under. Further, this
        electronic record is generated by a computer system and does not require
        any physical or digital signatures. This electronic record is published
        in accordance with the relevant provisions of the Information Technology
        Act, 2000 and rules made there under.
      </p>
      <h3>1. PLATFORM</h3>
      <p>
        Please note that the domain name Guzoye.com (the “Website”); is owned
        and operated by Real Hilme private limited company, a private limited
        company incorporated and existing in accordance with the laws of
        ethiopia and having its registered office at Addis Ababa 4 kilo, Iklhas
        Building.
      </p>
      <h3>2. LEGAL AGREEMENT</h3>
      <p>
        2.1 These terms and conditions of use (“Terms of Use’’) govern the use
        and access of Platform and/or availing of the Services (as defined
        below) through the Platform; or through any of the Authorised Channels
        and constitutes a legal agreement between the Company, and
        you/yourself/yourselves (“User(s)”). A User shall mean and include any
        person who access the Platform, uses Services offered through the
        Platform or through any of the Authorised Channels and/or is desirous of
        and makes booking on the Platform for availing the Transportation
        Services (as defined below) offered by Third Party Operators(as defined
        below) through the Platform.
      </p>
      <p>
        2.2 Your use and access to the Platform/Services, availing the
        Transportation Services provided by Third Party Operators through the
        Platform or through any of the Authorised Channels, is subject to the
        guidelines, rules, privacy policy, terms, conditions and/or other
        applicable policies and procedures (“Company Policy(ies)”) applicable to
        such Service, which shall be posted on the Platform from time to time.
        Unless otherwise provided for in any specific Company Policy, the
        Company Policies shall be deemed to be incorporated into this Terms of
        Use and shall be considered as part and parcel of hereof and Terms of
        Use together with the Company Policies constitute the entire legal
        binding agreement between the User and the Company. Therefore, by
        impliedly or expressly agreeing to be bound by the Terms of Use, you
        also agree to be bound by the Company Policies, as may be updated,
        amended or revised from time to time.
      </p>
      <p>
        2.3 If you do not agree with the Terms of Use, please do not access and
        use the Platform or our Service (defined later) through any means. If
        you continue to use and/or access the Platform and availing the
        Services/Transportation Services provided by Third Party Operators
        through the Platform or through any of the Authorised Channels, you are
        agreeing to comply with and be bound by the Terms of Use.
        <p>
          2.4 Guzoye
        reserves the right, to modify or replace, in part or full, any of these
        Terms of Use, or change, suspend, block, discontinue or restrict your
        use to all or any feature of the Service or Platform at any time. 2.5
        Guzoye shall not be required to notify the User of any changes made to
        these Terms of Use. The revised Terms of Use shall be made available on
        the Platform. The User is requested to visit the Website and/or
        Application to view the most current Terms of Use. The User can
        determine when Guzoye last modified the Terms of Use by referring to the
        “Last Updated” legend above. It shall be User’s responsibility to check
        these Terms of Use periodically for changes. Guzoye may require the User
        to provide User’s consent to the updated Terms of Use in a specified
        manner prior to any further use and access of the Platform and/or
        availing the Services/Transportation Services offered by Third Party
        Operators through the Platform or any Authorised Channels. If no such
        separate consent is sought, User’s continued use of the Platform and
        availing the Services/Transportation Services, following the changes to
        the Terms of Use, will constitute User’s acceptance of those changes.
        User’s use and access of the Platform and/or availing the
        Services/Transportation Services is subject to the most current version
        of the Terms of Use made available on the Platform at the time of such
        use.
        </p> 
      </p>
      <h3>DEFINITIONS</h3>
      <p>
        All the defined and capitalized terms used in the Terms of Use will have
        the meaning as assigned to them herein below or as assigned to them in
        the relevant clauses of these Terms of Use: </p>
        <p>3.1 “Additional Charges”
        shall mean such charges as may be charged towards consumption of any
        additional services like excess freight, insurance, food items, water,
        beverages etc. while undertaking a trip, in addition to the cost and
        charges for availing the Transportation Services. 3.2 “Account” shall
        mean the account created by the User on the Platform for using and
        accessing the Platform/Services and for availing the Transportation
        Services offered and provided by Third Party Operators through the
        Platform.</p>
        <p>3.3 “Applicable Law(s)” means any applicable law, rule,
        regulation, ordinance, order, treaty, judgment, notification, decree,
        bye-law, governmental approval, directive, guideline, requirement or
        other governmental restriction, or any similar form of decision of, or
        determination by, or any interpretation, policy or administration,
        having the force of law and shall include any of the foregoing,
        injunction, permit or decision of any central, state or local, municipal
        government, authority, agency, courthaving jurisdiction over the matter
        in question. </p>
        <p>3.4 “Authorised Channels” shall mean the authorised
        resellers/partner/agent, third party platform engaged by YOLO to provide
        Services, through which the Transportation Services of the Operator are
        offered by YOLO to the Users/passengers in accordance with these Terms
        of Use. 3.5 “Brand” shall mean the brand name of the Company i.e. the
        name and style of “Yolo” and the operating under the logo and shall
        include any other brand name, under which the Company carries out its
        business activities.</p>
        <p>3.6 “Booking(s)” shall mean and include any/all
        orders or requests placed by the User for availing the Transportation
        Services offered by the Third-PartyOperator(s) through the Platform or
        through the Authorised Channels.</p>
        <p>3.7 “Booking Price” shall mean the
        aggregate amount reflected on the Platform in respect of a Ticket,
        including, inter alia, the fare payable by the User for availing and
        provision of the Transportation Services in a Bus, any fee or levy,
        tolls and applicable taxes presently payable or hereinafter imposed by
        the law or required to be paid for availing of the Transportation
        Services though the Platform or through the Authorised Channels,
        technology fee, platform usage charges, Additional Charges (if any).</p>
            <p>3.8
        “Bus” or “Buses” shall mean the vehicles or buses belonging to the Third
        Party Operators meeting the pre-agreed specifications, which are made
        available for use to the Users who have made Bookings through the
        Platform or through the Authorised Channels; </p> 
        <p>3.9 “Third Party Operators”
        shall mean individuals/companies/sole proprietorship/firm, holding a
        contract carriage permit or such other permit or license as required and
        issued under the provisions of the Motor Vehicles Act,1988 or under any
        other Applicable Laws or any other person authorized by such permit
        holder, who are independent third-party service providers operating and
        managing the fleet of Buses together with the necessary staff including
        without limitation the drivers, conductors, maintenance staff, mechanics
        who shall assist in the operation of Buses for the purposes of provision
        of Transportation Service to the Users through the Platform or through
        the Authorised Channels; </p>
        <p>3.10 “Cancellation Fee” shall mean such fee as
        charged in respect of cancelled Trips as notified to the User at the
        time of making a Booking on the Platform or through the Authorised
        Channels, the same to be levied in terms of Clause 11 and in accordance
        with cancellation and refund policy provided on the Platform and the
        Tickets.</p>
        <p> 3.11 “City of Operation” shall mean a city in which the Users
        avails and Third Party Operators render the Transportation Services
        respectively. </p> 
        <p>3.12 “Force Majeure Event” shall mean any event arising
        due to any cause beyond the reasonable control of the Company and the
        Third Party Operator, including insolvency, business exigencies,
        operational technical issues, labor unrest, war, commotion, armed
        conflict, invasion, hostilities, riot, rebellion, revolution, civil war,
        riot, insurrection, acts of God, epidemics, natural
        calamities/disasters, strikes, lock out, change of Applicable Law, which
        materially restricts provisions of Services or Transportation Services
        offered on the Platform etc.</p>
        <p> 3.13 “Registration Data” shall mean and
        include the present, valid, true and accurate name, email ID, phone
        number and such other information as may be required by YOLO from the
        User from time to time for registration on the Platform.</p> 
        <p>
          3.14 “Ticket”
        shall mean a voucher confirming the Booking made by a User for availing
        Transportation Services of the Third Party Operators through the
        Platform or through the Authorised Channels, specifying details like
        travel route, price, travel destination and other details of the
        Booking, as circulated by YOLO upon confirmation of every Booking and as
        appearing in the Account of every User for easy reference.
        </p> <p> 3.15 “Trip”
        shall mean the travel in the Bus by the User, facilitated through
        Booking made on the Platform by purchasing a Ticket for a particular
        Trip.</p>
        <p>  3.16 “Service(s)” shall mean the provision of technology services
        available on/through the Platform or the Authorised Channels that
        enables the Users, who are desirous of obtaining, availing, arranging,
        scheduling Transportation Services offered by Third Party Operators by
        making Bookings and purchasing Tickets in respect of the Trips to be
        undertaken by the Buses of the Third Party Operators on pre-agreed
        routes. For avoidance of any doubt, it is clarified that YOLO is a mere
        intermediary which facilitates and enables the Users to avail and the
        Third Party Operators to provide the Transportation Service on the Bus
        facilitated by the Platform.</p> 
        <p>
           3.17 “Terms of Use” shall mean these terms
        and conditions for the User. 3.18 “Third- Party Advertiser(s)” online or
        offline advertisements of various sponsors advertising and marketing
        their own goods and services through YOLO or on the Platform. 
        </p>
        <p>3.19
        “Transportation Service(es)” shall mean the services for
        carriage/transportation of the Users from one point to another in the
        Buses on pre-determined/agreed routes offered and provided by Third
        Party Operator facilitated by YOLO through the Platform or through the
        Authorised Channels.</p>
      </p>
    </div>
     <footer id="footer">
      <div id="footerimg">
        <img src="image/Logo-wz-bk.png" alt="Logo" />
        <p>
          Guzoye provides safe, trusted, and standardize travel option around
          ethiopia's ling distance routes, operating across 100+ routes in 11
          states. its companion brand, provides comprehensive train travel
          information, serving over 1000+ users monthly.
        </p>
      </div>
      <div id="foot_book">
        <h2>Book With Us</h2>
        <p>
          <a href="index.php">Bus Tickets</a> <br />
          <a href="booking.php">My Booking</a> <br />
          <br />
          <br />
          <br />
        </p>
      </div>
      <div>
        <h2>Info</h2>
        <p>
          <a href="aboutus.php">About Us</a> <br />
          <a href="contact.php">Contact Us</a> <br />
          <a href="termandcondition.php">Terms & Conditions</a> <br />
          <a href="faq.php">FAQ</a>
        </p>
        <br />
      </div>
    </footer>

    <div id="footerbottom">
      <br />
      Copyright &copy; 2022. All Rights Reserved. <br />
    </div>
  </body>
</html>
